export const DATA_REQUEST = "DATA_REQUEST";
export const DATA_REQUEST_SUCCESS = "DATA_REQUEST_SUCCESS";
export const DATA_REQUEST_ERROR = "DATA_REQUEST_ERROR";
export const UPDATE_USERS = "UPDATE_USERS";
export const SET_LOADING_DATA = "SET_LOADING_DATA";
export const UPDATE_FILTERED_USERS = "UPDATE_FILTERED_USERS";